name:  Dental Lab Web CD Prod

on: 
  push:
    branches:
        - main
    tags:
        - v[0-9]+.[0-9]+.[0-9]+

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.9.5
  INFRA_DIRECTORY: ./infrastructure
  ENV: prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform init
        run: terraform init
        working-directory: $ {{ env.INFRA_DIRECTORY }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.INFRA_DIRECTORY }}

      - name: Terraform workspace select
        run: terraform workspace select ${{ env.ENV }}
        working-directory: ${{ env.INFRA_DIRECTORY }}

      - name: Login to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{ steps.ecr_login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY_NAME: dlw-${{ env.ENV }}-repository
        run: |
          docker build -t $REPOSITORY_NAME .
          docker tag $REPOSITORY_NAME:$IMAGE_TAG $ECR_REGISTRY/$REPOSITORY_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPOSITORY_NAME:$IMAGE_TAG
  
      - name: Terraform plan
        env:
          IMAGE_ECR_URI: ${{ steps.ecr_login.outputs.registry }}/dlw-${{ env.ENV }}-repository:${{ github.sha }}
        run: terraform plan -var="image_ecr_uri=${IMAGE_ECR_URI}"
        working-directory: ${{ env.INFRA_DIRECTORY }}

      - name: Terraform apply
        env:
          IMAGE_ECR_URI: ${{ steps.ecr_login.outputs.registry }}/dlw-${{ env.ENV }}-repository:${{ github.sha }}
        run: terraform apply -auto-approve -var="image_ecr_uri=${IMAGE_ECR_URI}"
        working-directory: ${{ env.INFRA_DIRECTORY }}
